### ISSUE TITLE
Bug "@"

### ISSUE THREAD

**Issue by liveinno** [mo-azfar/OTRS-CustomMessage-API#1]
https://github.com/mo-azfar/OTRS-CustomMessage-API/blob/7fed2c878a4dc27a447ca03f4675d986af111c04/Custom/Kernel/System/CustomMessage.pm#L74

 text=>"$Param{Message}",

**Comment by mo-azfar** [comment]
Just tested it..i have no issue when passing @ in the body..
perhaps due i have different perl version or additional perl module..
however, i updated the code to include "".

https://github.com/mo-azfar/OTRS-CustomMessage-API/commit/4ee3904873bc5383409449c65c234bf56c8ecc07

Thanks :)
